PROYECTO INTEGRADOR 2026 "PRODUCTORA AVICOLA"

INTEGRANTES: - SANTIAGO MONTENEGRO
             
             - MATEO SCATOLON

             - DYLAN BOGADO

             - ALAN CHAMORRO

             - JOSUE HIDALGO
